image: node:14

stages:
  - build
  - test
  - lint
  - package
  - publish
  - deploy


before_script:
  - dos2unix publish.sh
  - chmod +x publish.sh

build:
  stage: build
  script:
    - echo "Building the application..."
    - npm install

lint:
  stage: test
  script:
    - echo "Linting the application..."
    - npm run lint  # Assuming you have a lint script in your package.json

test:
  stage: test
  script:
    - echo "Running tests..."
    - npm test

package:
  stage: package
  script:
    - echo "Packaging the application..."
    - npm pack
  artifacts:
    paths:
      - $CI_PROJECT_NAME-$CI_COMMIT_TAG.tgz

publish:
  stage: publish
  script:
    - ./publish.sh
  only:
    - main  # Only publish from the main branch
    
deploy:
  stage: deploy
  script:
    - echo "Deploying the application..."
    - npm start
  only:
    - main  # Only deploy from the main branch
